###
# register new admisn into system

POST http://localhost:4000/v1/auth/register/admin
Content-Type: application/json

{
    "firstname":"Morgana",
    "lastname":"Penndragon",
    "username":"morgana",
    "email":"morgana@gmail.com",
    "phone_number":"0732945678",
    "password":"@Lance25"
}

###
# login existing admin into system

POST http://localhost:4000/v1/auth/login/admin
Content-Type: application/json

{
    "username_or_email":"morgana@gmail.com",
    "password":"@Lance25"
}

###
