###
# register new admisn into system

POST http://localhost:4000/v1/auth/register/admin
Content-Type: application/json

{
    "first_name":"Lancelot",
    "last_name":"Sir",
    "user_name":"sirlance",
    "user_email":"lance@gmail.com",
    "phone_number":"0712345678",
    "password":"@Lance25"
}

###
# login existing admin into system

POST http://localhost:4000/v1/auth/login/admin
Content-Type: application/json

{
    "userNameOrEmail":"sirlance",
    "password":"@Lance25"
}

###
