###
# add new members to system
POST http://localhost:4000/v1/members
Content-Type: application/json

{
    "admin_id":"09d05331-7977-423f-9dcf-905c46084aa9",
    "microfinance_id":"5d76e5c1-4c91-4897-a98a-a4cb6a022418",
    "firstname":"lancelot",
    "lastname":"mucheru",
    "username":"lance",
    "email":"lance@gmail.com",
    "phone_number":"0771795971",
    "password":"@Lance25"
}

###
# get all members
GET http://localhost:4000/v1/members

###
# activate exixting members in system
PUT localhost:4000/v1/members/activate/09d05331-7977-423f-9dcf-905c46084aa9
Content-Type: application/json

{
    "user_id":"61aea8a1-9c03-4670-bc31-118599caa922"
}
###
