###
# add new members to system
POST http://localhost:4000/v1/members
Content-Type: application/json

{
    "admin_id":"09d05331-7977-423f-9dcf-905c46084aa9",
    "microfinance_id":"c23848b5-4408-4671-8d76-83b6fb30e325",
    "firstname":"perceival",
    "lastname":"mucheru",
    "username":"percy",
    "email":"percy@gmail.com",
    "phone_number":"0711795971",
    "password":"@Lance25"
}

###
# get all members
GET http://localhost:4000/v1/members

###
# activate exixting members in system
PUT http://localhost:4000/v1/members/activate/09d05331-7977-423f-9dcf-905c46084aa9
Content-Type: application/json

{
    "user_id":"7b80a07f-5c33-4cac-8518-cd8732ac7f3d"
}
###
# update user
PUT http://localhost:4000/v1/members/update/09d05331-7977-423f-9dcf-905c46084aa9
Content-Type: application/json

{
    "user_id": "2138bb62-3ac2-4960-bf2a-29860462632a",
    "microfinance_id": "c23848b5-4408-4671-8d76-83b6fb30e325",
    "firstname": "mkuu",
    "lastname": "bana",
    "username": "whiteKnight",
    "password": "@Lance25"
}

###
# delete a member
PUT http://localhost:4000/v1/members/delete/09d05331-7977-423f-9dcf-905c46084aa9
Content-Type: application/json

{
    "user_id": "fce397db-714a-4f4b-8478-1a019d80c1d6"
}
