###
# create new microfinance

POST http://localhost:4000/v1/microfinances
Content-Type: application/json

{
    "reg_number":"0001",
    "name":"Round Table",
    "email":"roundtable@gmail.com",
    "phone_number":"0712345678",
    "location":"nairobi"
}

###
# get all microfinances

GET http://localhost:4000/v1/microfinances

###
# update microfinance

PUT http://localhost:4000/v1/microfinances/update/09d05331-7977-423f-9dcf-905c46084aa9
Content-Type: application/json

{
    "microfinance_id":"c23848b5-4408-4671-8d76-83b6fb30e325",
    "reg_number":"0002",
    "name":"Magneto Sacco",
    "email":"kinara@sacco.com",
    "phone_number":"0754523554",
    "location":"mombasa"
}
###
# delete microfinance

PUT http://localhost:4000/v1/microfinances/delete/09d05331-7977-423f-9dcf-905c46084aa9
Content-Type: application/json

{
    "microfinance_id":"b0664d71-be76-4251-878b-694c3a1b3ae2"
}

###
