###
# create new microfinance
POST http://localhost:4000/v1/microfinances
Content-Type: application/json

{
    "registration_number":"017",
    "sacco_name":"Wangwana",
    "sacco_email":"wangwana@gmail.com",
    "sacco_phone_number":"0712345678",
    "location":"kilimani"
}

###
# get all microfinances
GET http://localhost:4000/v1/microfinances

###

